project:
  type: website

website:
  title: ""
  navbar: false
  favicon: favicon.ico

format:
  html:
    css: styles.css
    include-in-header:
      - _partials/nav.html
    toc: false
    page-layout: full
    # include-in-header:
    #   text: |
    #     <meta name="description" content="Data-driven analysis of Nepal's public finance, governance, and political economy.">
    # include-before-body: _partials/nav.html
    include-after-body: _partials/footer.html